version: '3.8'

services:
  backend:
    build:
      context: ./movie_dashboard
      dockerfile: Dockerfile
    image: movie-dashboard-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=movie_dashboard.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./movie-dashboard-frontend
      dockerfile: Dockerfile
    image: movie-dashboard-frontend:latest
    ports:
      - "3000:5000"  # Serve will use port 5000 by default

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
